# Generated by Django 3.2 on 2021-04-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolistitem',
            options={'ordering': ('-created_at', '-dead_line', 'item_name', 'status')},
        ),
        migrations.AlterModelOptions(
            name='todolists',
            options={'ordering': ('-created_at',)},
        ),
    ]
