# Generated by Django 3.1.6 on 2021-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210414_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('On Progress', 'On Progress'), ('Expired', 'Expired')], default='On Progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='todolists',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
